#!/bin/bash

# Makes this script exit on first error.
set -e

# Activate VirtualEnv
source bin/activate
source /opt/ros/indigo/setup.bash
source ~/catkin_ws/devel/setup.bash

# Run unit tests
pytest buzzmobile/tests/simulation

