#!/bin/bash

# Makes this script exit on first error.
set -e

# Activate VirtualEnv
source bin/activate

# Run pylint on all files
find . -name "*.py" -exec pylint --rcfile=ci_scripts/pylint/pylintrc {} \;
