#!/bin/bash

# Makes this script exit on first error.
set -e

# Activate VirtualEnv
source bin/activate
source /opt/ros/indigo/setup.sh
source ../../devel/setup.sh

# Run pylint on all files
pylint buzzmobile --rcfile=ci_scripts/pylint/pylintrc
