#!/bin/bash

# Makes this script exit on first error.
set -e

# Activate VirtualEnv
source ~/catkin_ws/src/buzzmobile/bin/activate
source /opt/ros/indigo/setup.bash
source ~/catkin_ws/devel/setup.bash

# Run pylint on all files
pylint buzzmobile --rcfile=ci_scripts/pylint/pylintrc
