#!/bin/bash

# Makes this script exit on first error.
set -e

# Activate VirtualEnv
source bin/activate
source /opt/ros/indigo/setup.sh
source ../../devel/setup.sh

# spin up roscore
roscore&
PID1=$!
sleep 2

# Run unit tests
pytest buzzmobile/tests/

# kill roscore when we are done
kill $PID1
sleep 2
