#!/bin/bash

# Makes this script exit on first error.
set -e

# Activate VirtualEnv
source bin/activate
source /opt/ros/indigo/setup.bash
source ~/catkin_ws/devel/setup.bash

# Some tests import buzzmobile.msg, which is in ~/catkin_ws/devel
# If bozzmobile is a visible folder, then the correct one won't be visible
# So cd into buzzmobile
cd buzzmobile

# Run unit tests
pytest tests/unit

